# Generated by Django 2.2.6 on 2019-10-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=300)),
                ('urlToImage', models.CharField(max_length=300)),
                ('publishedAt', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=600)),
            ],
        ),
    ]
