# Generated by Django 2.2.6 on 2019-10-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesFromApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_author', models.CharField(max_length=40)),
                ('articles_title', models.CharField(max_length=200)),
                ('articles_description', models.CharField(max_length=1000)),
                ('articles_url', models.CharField(max_length=100)),
            ],
        ),
    ]
