# Generated by Django 2.2.6 on 2019-10-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesFromApi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('articles_author', models.CharField(blank=True, max_length=40, null=True)),
                ('articles_title', models.CharField(blank=True, max_length=200, null=True)),
                ('articles_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('articles_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
