# Generated by Django 2.2.6 on 2019-10-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsArticles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesfromapi',
            name='articles_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
