# Generated by Django 2.2.6 on 2019-11-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsArticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluserfavorite',
            name='news_id',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
