# Generated by Django 2.2.6 on 2019-11-07 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsArticles', '0002_auto_20191101_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('cluster_headline', models.CharField(max_length=250)),
                ('cluster_summary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSummary',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('headline', models.CharField(max_length=250)),
                ('summary', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Published')),
                ('sum_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Summarized')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('news_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsArticles.NewsSummary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsArticles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsArticles.Cluster')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsArticles.User')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsArticles.NewsSummary')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsArticles.User')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='news_summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsArticles.NewsSummary'),
        ),
    ]
