# Generated by Django 2.2.6 on 2019-11-07 04:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsArticles', '0003_auto_20191107_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssummary',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
