# Generated by Django 2.2.6 on 2019-11-07 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('newsArticles', '0004_auto_20191107_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='cluster_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
